-- MySQL Script generated by MySQL Workbench
-- Sun Mar 19 18:54:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `id` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `apellido` VARCHAR(50) NULL,
  `nombreCompleto` LONGTEXT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seccion` (
  `id` INT NULL AUTO_INCREMENT,
  `titulo` LONGTEXT NULL,
  `descripcion` LONGTEXT NULL,
  `dataBsTarget` VARCHAR(50) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_seccion_persona_idx` (`persona_id` ASC),
  CONSTRAINT `fk_seccion_persona`
    FOREIGN KEY (`persona_id`)
    REFERENCES `mydb`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`banner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`banner` (
  `id` INT NULL AUTO_INCREMENT,
  `titulo` LONGTEXT NULL,
  `subtitulo` LONGTEXT NULL,
  `imagen` LONGTEXT NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_banner_persona1_idx` (`persona_id` ASC),
  CONSTRAINT `fk_banner_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `mydb`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`acerca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`acerca` (
  `id` INT NULL AUTO_INCREMENT,
  `titulo` LONGTEXT NULL,
  `subtitulo` LONGTEXT NULL,
  `foto` LONGTEXT NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_acerca_persona1_idx` (`persona_id` ASC),
  CONSTRAINT `fk_acerca_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `mydb`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`experiencia` (
  `id` INT NULL AUTO_INCREMENT,
  `descripcion` LONGTEXT NULL,
  `seccion_id` INT NOT NULL,
  `seccion_persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `seccion_id`, `seccion_persona_id`),
  INDEX `fk_experiencia_seccion1_idx` (`seccion_id` ASC, `seccion_persona_id` ASC),
  CONSTRAINT `fk_experiencia_seccion1`
    FOREIGN KEY (`seccion_id` , `seccion_persona_id`)
    REFERENCES `mydb`.`seccion` (`id` , `persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`educacion` (
  `id` INT NULL AUTO_INCREMENT,
  `imagen` LONGTEXT NULL,
  `alt` VARCHAR(50) NULL,
  `classImg` VARCHAR(50) NULL,
  `tituloCarta` VARCHAR(50) NULL,
  `descripcionCarta` LONGTEXT NULL,
  `boton` VARCHAR(30) NULL,
  `href` LONGTEXT NULL,
  `modal` TINYINT NULL,
  `target` VARCHAR(50) NULL,
  `dataBsTarget` VARCHAR(50) NULL,
  `seccion_id` INT NOT NULL,
  `seccion_persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `seccion_id`, `seccion_persona_id`),
  INDEX `fk_educacion_seccion1_idx` (`seccion_id` ASC, `seccion_persona_id` ASC),
  CONSTRAINT `fk_educacion_seccion1`
    FOREIGN KEY (`seccion_id` , `seccion_persona_id`)
    REFERENCES `mydb`.`seccion` (`id` , `persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`skill` (
  `seccion_id` INT NOT NULL,
  `seccion_persona_id` INT NOT NULL,
  PRIMARY KEY (`seccion_id`, `seccion_persona_id`),
  CONSTRAINT `fk_skill_seccion1`
    FOREIGN KEY (`seccion_id` , `seccion_persona_id`)
    REFERENCES `mydb`.`seccion` (`id` , `persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`softSkill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`softSkill` (
  `id` INT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NULL,
  `porcentaje` INT NULL,
  `skill_seccion_id` INT NOT NULL,
  `skill_seccion_persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `skill_seccion_id`, `skill_seccion_persona_id`),
  INDEX `fk_softSkill_skill1_idx` (`skill_seccion_id` ASC, `skill_seccion_persona_id` ASC),
  CONSTRAINT `fk_softSkill_skill1`
    FOREIGN KEY (`skill_seccion_id` , `skill_seccion_persona_id`)
    REFERENCES `mydb`.`skill` (`seccion_id` , `seccion_persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`hardSkill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hardSkill` (
  `id` INT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NULL,
  `porcentaje` INT NULL,
  `color` VARCHAR(50) NULL,
  `skill_seccion_id` INT NOT NULL,
  `skill_seccion_persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `skill_seccion_id`, `skill_seccion_persona_id`),
  INDEX `fk_hardSkill_skill1_idx` (`skill_seccion_id` ASC, `skill_seccion_persona_id` ASC),
  CONSTRAINT `fk_hardSkill_skill1`
    FOREIGN KEY (`skill_seccion_id` , `skill_seccion_persona_id`)
    REFERENCES `mydb`.`skill` (`seccion_id` , `seccion_persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proyecto` (
  `id` INT NULL AUTO_INCREMENT,
  `imagen` LONGTEXT NULL,
  `alt` VARCHAR(50) NULL,
  `tituloCarta` VARCHAR(50) NULL,
  `descripcionCarta` LONGTEXT NULL,
  `boton` VARCHAR(30) NULL,
  `imgBtn` TINYINT NULL,
  `srcImgBtn` LONGTEXT NULL,
  `href` LONGTEXT NULL,
  `altBtn` VARCHAR(30) NULL,
  `modal` TINYINT NULL,
  `target` VARCHAR(50) NULL,
  `dataBsTarget` VARCHAR(50) NULL,
  `seccion_id` INT NOT NULL,
  `seccion_persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `seccion_id`, `seccion_persona_id`),
  INDEX `fk_proyecto_seccion1_idx` (`seccion_id` ASC, `seccion_persona_id` ASC),
  CONSTRAINT `fk_proyecto_seccion1`
    FOREIGN KEY (`seccion_id` , `seccion_persona_id`)
    REFERENCES `mydb`.`seccion` (`id` , `persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`idiomaSkill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`idiomaSkill` (
  `id` INT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NULL,
  `porcentaje` INT NULL,
  `color` VARCHAR(50) NULL,
  `skill_seccion_id` INT NOT NULL,
  `skill_seccion_persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `skill_seccion_id`, `skill_seccion_persona_id`),
  INDEX `fk_idiomaSkill_skill1_idx` (`skill_seccion_id` ASC, `skill_seccion_persona_id` ASC),
  CONSTRAINT `fk_idiomaSkill_skill1`
    FOREIGN KEY (`skill_seccion_id` , `skill_seccion_persona_id`)
    REFERENCES `mydb`.`skill` (`seccion_id` , `seccion_persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
